name: swaap
description: "A new Flutter project."


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: ^3.8.1



#----------PACKAGES----------#
dependencies:
  flutter:
    sdk: flutter

    #Utility Packages

  #Icons  
  cupertino_icons: ^1.0.8



#---------- ./PACKAGES END/. ----------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true

  #----------LOCAL ASSETS----------#
assets:
  - assets\icons\
  - assets\images\
  - assets\logos\
